kumuluzee:
  name: rso-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      #connection-url: jdbc:postgresql://192.168.99.100:5432/customer
      connection-url: jdbc:postgresql://193.2.176.196:5432/userTable
      username: dbuser
      password: postgres
      max-pool-size: 20
#rest-properties:
#  external-services:
#    order-service:
#      enabled: true
