kumuluzee:
  name: rso-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://google/userTable
      cloudSqlInstance: rso-teamlj:europe-north1:users-instance
      socketFactory: com.google.cloud.sql.postgres.SocketFactory
      user: user
      password: midva
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
    discovery:
      etcd:
        hosts: http://localhost:2379
  app-properties:
    external-services:
      enabled: false
