apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: ls8856/rso-teamlj-users:1.6
        command: [ "echo", "SUCCESS" ]
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: gcloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://35.240.79.227:8080
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
